Map {
    Name: Null;
    TileSize: 48;
    ActiveCamera: EditorCamera {
        PostEffect: Null;
        Viewport: [0 0 1280 800];
        Position: [576 192];
        Scale: 1;
        Rotation: 0;
        Shake: 0;
        Follow: Null;
        MoveSpeed: 1000;
    };
    TilesImage: "Data\\Textures/tiles.png";
    Tiles: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0];
    Width: 24;
    Height: 8;
    Decals: [];
    Triggers: [];
    State: MapState {
        entities: [
            ActorInstance {
                Class: @"Defs/Entities/Player.ent.tk";
                Faction: Factions [Player];
                Controller: Null;
                CurrentHealth: 500;
                MaxSpeed: 400;
                Weapon: GunInstance {
                    Class: GunClass {
                        Projectile: @"Defs/Entities/Missile.ent.tk";
                        MaxAmmo: 300;
                        BurstCont: 0;
                        ShotsPerBurst: 1;
                        ErrorAngle: [0 0];
                        Name: Null;
                        Delay: [
                            100
                            100
                        ];
                        UnderchargeAction: UnderchargeAction.Dissipate;
                        OverchargeAction: OverchargeAction.Discharge;
                    };
                    CurrentAmmo: 300;
                    NextShot: 0;
                };
                Name: Null;
                Position: [134 155];
                Direction: [0.9989581 -0.04563629];
                Velocity: [0 0];
                State: StateMachine {
                    State: EntStateId.Idle;
                    Instance: EntStateInstance {
                        Id: EntStateId.Idle;
                        Class: EntStateClass {
                            Name: Null;
                            Sprite: Sprite {
                                ElapsedTime: 22476;
                                FrameCount: 2;
                                FrameLength: 100;
                                TotalLength: 200;
                                IsLooping: True;
                                Texture: "Data\\Textures/Entities/Player.png";
                                Width: 48;
                                Height: 48;
                                Size: [48 48];
                                ClipRect: [0 0 96 48];
                                Origin: [24 24];
                                Tween: TweenStyle.Overlap;
                                ShrinkToFit: True;
                            };
                            Radius: 24;
                        };
                        ElapsedTime: 0;
                    };
                    Transitions: {
                    };
                };
                OutlineColor: [0 0 0 0];
                SpawnTime: 0;
            }
            ActorInstance {
                Class: @"Defs/Entities/Astrovirus.ent.tk";
                Faction: Factions [Enemy Virus Common];
                Controller: Null;
                CurrentHealth: 40;
                MaxSpeed: 294.5054;
                Weapon: Null;
                Name: Null;
                Position: [254 95];
                Direction: [1 0];
                Velocity: [0 0];
                State: StateMachine {
                    State: EntStateId.Idle;
                    Instance: EntStateInstance {
                        Id: EntStateId.Idle;
                        Class: EntStateClass {
                            Name: Null;
                            Sprite: Sprite {
                                ElapsedTime: 35337;
                                FrameCount: 6;
                                FrameLength: 50;
                                TotalLength: 300;
                                IsLooping: True;
                                Texture: "Data\\Textures/Entities/Astrovirus.png";
                                Width: 40;
                                Height: 40;
                                Size: [40 40];
                                ClipRect: [0 0 240 120];
                                Origin: [20 20];
                                Tween: TweenStyle.Overlap;
                                ShrinkToFit: True;
                            };
                            Radius: 20;
                        };
                        ElapsedTime: 0;
                    };
                    Transitions: {
                    };
                };
                OutlineColor: [0 0 0 0];
                SpawnTime: 0;
            }
            ActorInstance {
                Class: @"Defs/Entities/Astrovirus.ent.tk";
                Faction: Factions [Enemy Virus Common];
                Controller: Null;
                CurrentHealth: 40;
                MaxSpeed: 279.4074;
                Weapon: Null;
                Name: Null;
                Position: [290 147];
                Direction: [1 0];
                Velocity: [0 0];
                State: StateMachine {
                    State: EntStateId.Idle;
                    Instance: EntStateInstance {
                        Id: EntStateId.Idle;
                        Class: EntStateClass {
                            Name: Null;
                            Sprite: Sprite {
                                ElapsedTime: 35337;
                                FrameCount: 6;
                                FrameLength: 50;
                                TotalLength: 300;
                                IsLooping: True;
                                Texture: "Data\\Textures/Entities/Astrovirus.png";
                                Width: 40;
                                Height: 40;
                                Size: [40 40];
                                ClipRect: [0 0 240 120];
                                Origin: [20 20];
                                Tween: TweenStyle.Overlap;
                                ShrinkToFit: True;
                            };
                            Radius: 20;
                        };
                        ElapsedTime: 0;
                    };
                    Transitions: {
                    };
                };
                OutlineColor: [0 0 0 0];
                SpawnTime: 0;
            }
            ActorInstance {
                Class: @"Defs/Entities/Cyst.ent.tk";
                Faction: Factions [Enemy];
                Controller: ArtilleryController {
                    MaxRange: 200;
                    CanRotate: False;
                    ShowSweepLines: True;
                    trackedActor: Null;
                };
                CurrentHealth: 1000;
                MaxSpeed: 0;
                Weapon: SpawnerInstance {
                    Class: SpawnerClass {
                        Spawns: [
                            [
                                @"Defs/Entities/InfectedCell.ent.tk"
                                [3 5]
                            ]
                        ];
                        Name: Null;
                        Delay: [
                            1000
                            3000
                        ];
                        UnderchargeAction: UnderchargeAction.Dissipate;
                        OverchargeAction: OverchargeAction.Discharge;
                    };
                    SpawnQueue: Null;
                    NextShot: 0;
                };
                Name: Null;
                Position: [560.7941 22.09216];
                Direction: [-4.371139E-08 1];
                Velocity: [0 0];
                State: StateMachine {
                    State: EntStateId.Idle;
                    Instance: EntStateInstance {
                        Id: EntStateId.Idle;
                        Class: EntStateClass {
                            Name: Null;
                            Sprite: Sprite {
                                ElapsedTime: 34171;
                                FrameCount: 1;
                                FrameLength: 0;
                                TotalLength: 0;
                                IsLooping: False;
                                Texture: "Data\\Textures/Entities/Spawner.png";
                                Width: 64;
                                Height: 64;
                                Size: [64 64];
                                ClipRect: [0 0 64 64];
                                Origin: [32 32];
                                Tween: TweenStyle.None;
                                ShrinkToFit: True;
                            };
                            Radius: 32;
                        };
                        ElapsedTime: 0;
                    };
                    Transitions: {
                    };
                };
                OutlineColor: [0 0 0 0];
                SpawnTime: 0;
            }
            ActorInstance {
                Class: @"Defs/Entities/Ebola.ent.tk";
                Faction: Factions [Enemy];
                Controller: Null;
                CurrentHealth: 500;
                MaxSpeed: 213.7508;
                Weapon: Null;
                Name: Null;
                Position: [742.8334 143.0873];
                Direction: [-0.9863939 0.164399];
                Velocity: [0 0];
                State: StateMachine {
                    State: EntStateId.Idle;
                    Instance: EntStateInstance {
                        Id: EntStateId.Idle;
                        Class: EntStateClass {
                            Name: Null;
                            Sprite: Sprite {
                                ElapsedTime: 39426;
                                FrameCount: 4;
                                FrameLength: 100;
                                TotalLength: 400;
                                IsLooping: True;
                                Texture: "Data\\Textures/Entities/Ebola.png";
                                Width: 54;
                                Height: 16;
                                Size: [54 16];
                                ClipRect: [0 0 108 32];
                                Origin: [27 8];
                                Tween: TweenStyle.Overlap;
                                ShrinkToFit: True;
                            };
                            Radius: 27;
                        };
                        ElapsedTime: 0;
                    };
                    Transitions: {
                    };
                };
                OutlineColor: [0 0 0 0];
                SpawnTime: 0;
            }
            ActorInstance {
                Class: @"Defs/Entities/Huge.ent.tk";
                Faction: Factions [Enemy Boss];
                Controller: Null;
                CurrentHealth: 5000;
                MaxSpeed: 0;
                Weapon: Null;
                Name: Null;
                Position: [994.8235 176.1559];
                Direction: [-1 8.742278E-08];
                Velocity: [0 0];
                State: StateMachine {
                    State: EntStateId.Idle;
                    Instance: EntStateInstance {
                        Id: EntStateId.Idle;
                        Class: EntStateClass {
                            Name: Null;
                            Sprite: Sprite {
                                ElapsedTime: 27165;
                                FrameCount: 1;
                                FrameLength: 0;
                                TotalLength: 0;
                                IsLooping: True;
                                Texture: "Data\\Textures/Entities/Rhinovirus.png";
                                Width: 128;
                                Height: 128;
                                Size: [128 128];
                                ClipRect: [0 0 128 128];
                                Origin: [64 64];
                                Tween: TweenStyle.None;
                                ShrinkToFit: True;
                            };
                            Radius: 64;
                        };
                        ElapsedTime: 0;
                    };
                    Transitions: {
                    };
                };
                OutlineColor: [154 205 50 255];
                SpawnTime: 0;
            }
            ActorInstance {
                Class: @"Defs/Entities/Astrovirus.ent.tk";
                Faction: Factions [Enemy Virus Common];
                Controller: Null;
                CurrentHealth: 40;
                MaxSpeed: 275.5593;
                Weapon: Null;
                Name: Null;
                Position: [334 201];
                Direction: [1 0];
                Velocity: [0 0];
                State: StateMachine {
                    State: EntStateId.Idle;
                    Instance: EntStateInstance {
                        Id: EntStateId.Idle;
                        Class: EntStateClass {
                            Name: Null;
                            Sprite: Sprite {
                                ElapsedTime: 35337;
                                FrameCount: 6;
                                FrameLength: 50;
                                TotalLength: 300;
                                IsLooping: True;
                                Texture: "Data\\Textures/Entities/Astrovirus.png";
                                Width: 40;
                                Height: 40;
                                Size: [40 40];
                                ClipRect: [0 0 240 120];
                                Origin: [20 20];
                                Tween: TweenStyle.Overlap;
                                ShrinkToFit: True;
                            };
                            Radius: 20;
                        };
                        ElapsedTime: 0;
                    };
                    Transitions: {
                    };
                };
                OutlineColor: [0 0 0 0];
                SpawnTime: 0;
            }
            ActorInstance {
                Class: @"Defs/Entities/Astrovirus.ent.tk";
                Faction: Factions [Enemy Virus Common];
                Controller: Null;
                CurrentHealth: 40;
                MaxSpeed: 313.1478;
                Weapon: Null;
                Name: Null;
                Position: [326 253];
                Direction: [1 0];
                Velocity: [0 0];
                State: StateMachine {
                    State: EntStateId.Idle;
                    Instance: EntStateInstance {
                        Id: EntStateId.Idle;
                        Class: EntStateClass {
                            Name: Null;
                            Sprite: Sprite {
                                ElapsedTime: 35337;
                                FrameCount: 6;
                                FrameLength: 50;
                                TotalLength: 300;
                                IsLooping: True;
                                Texture: "Data\\Textures/Entities/Astrovirus.png";
                                Width: 40;
                                Height: 40;
                                Size: [40 40];
                                ClipRect: [0 0 240 120];
                                Origin: [20 20];
                                Tween: TweenStyle.Overlap;
                                ShrinkToFit: True;
                            };
                            Radius: 20;
                        };
                        ElapsedTime: 0;
                    };
                    Transitions: {
                    };
                };
                OutlineColor: [0 0 0 0];
                SpawnTime: 0;
            }
            ActorInstance {
                Class: @"Defs/Entities/Astrovirus.ent.tk";
                Faction: Factions [Enemy Virus Common];
                Controller: Null;
                CurrentHealth: 40;
                MaxSpeed: 354.8381;
                Weapon: Null;
                Name: Null;
                Position: [292 295];
                Direction: [1 0];
                Velocity: [0 0];
                State: StateMachine {
                    State: EntStateId.Idle;
                    Instance: EntStateInstance {
                        Id: EntStateId.Idle;
                        Class: EntStateClass {
                            Name: Null;
                            Sprite: Sprite {
                                ElapsedTime: 35337;
                                FrameCount: 6;
                                FrameLength: 50;
                                TotalLength: 300;
                                IsLooping: True;
                                Texture: "Data\\Textures/Entities/Astrovirus.png";
                                Width: 40;
                                Height: 40;
                                Size: [40 40];
                                ClipRect: [0 0 240 120];
                                Origin: [20 20];
                                Tween: TweenStyle.Overlap;
                                ShrinkToFit: True;
                            };
                            Radius: 20;
                        };
                        ElapsedTime: 0;
                    };
                    Transitions: {
                    };
                };
                OutlineColor: [0 0 0 0];
                SpawnTime: 0;
            }
            ActorInstance {
                Class: @"Defs/Entities/Astrovirus.ent.tk";
                Faction: Factions [Enemy Virus Common];
                Controller: Null;
                CurrentHealth: 40;
                MaxSpeed: 227.8641;
                Weapon: Null;
                Name: Null;
                Position: [248 213];
                Direction: [1 0];
                Velocity: [0 0];
                State: StateMachine {
                    State: EntStateId.Idle;
                    Instance: EntStateInstance {
                        Id: EntStateId.Idle;
                        Class: EntStateClass {
                            Name: Null;
                            Sprite: Sprite {
                                ElapsedTime: 35337;
                                FrameCount: 6;
                                FrameLength: 50;
                                TotalLength: 300;
                                IsLooping: True;
                                Texture: "Data\\Textures/Entities/Astrovirus.png";
                                Width: 40;
                                Height: 40;
                                Size: [40 40];
                                ClipRect: [0 0 240 120];
                                Origin: [20 20];
                                Tween: TweenStyle.Overlap;
                                ShrinkToFit: True;
                            };
                            Radius: 20;
                        };
                        ElapsedTime: 0;
                    };
                    Transitions: {
                    };
                };
                OutlineColor: [0 0 0 0];
                SpawnTime: 0;
            }
            ActorInstance {
                Class: @"Defs/Entities/Cyst.ent.tk";
                Faction: Factions [Enemy];
                Controller: ArtilleryController {
                    MaxRange: 200;
                    CanRotate: False;
                    ShowSweepLines: True;
                    trackedActor: Null;
                };
                CurrentHealth: 1000;
                MaxSpeed: 0;
                Weapon: SpawnerInstance {
                    Class: SpawnerClass {
                        Spawns: [
                            [
                                @"Defs/Entities/InfectedCell.ent.tk"
                                [3 5]
                            ]
                        ];
                        Name: Null;
                        Delay: [
                            1000
                            3000
                        ];
                        UnderchargeAction: UnderchargeAction.Dissipate;
                        OverchargeAction: OverchargeAction.Discharge;
                    };
                    SpawnQueue: Null;
                    NextShot: 0;
                };
                Name: Null;
                Position: [714.8578 365.102];
                Direction: [-4.371139E-08 -1];
                Velocity: [0 0];
                State: StateMachine {
                    State: EntStateId.Idle;
                    Instance: EntStateInstance {
                        Id: EntStateId.Idle;
                        Class: EntStateClass {
                            Name: Null;
                            Sprite: Sprite {
                                ElapsedTime: 34171;
                                FrameCount: 1;
                                FrameLength: 0;
                                TotalLength: 0;
                                IsLooping: False;
                                Texture: "Data\\Textures/Entities/Spawner.png";
                                Width: 64;
                                Height: 64;
                                Size: [64 64];
                                ClipRect: [0 0 64 64];
                                Origin: [32 32];
                                Tween: TweenStyle.None;
                                ShrinkToFit: True;
                            };
                            Radius: 32;
                        };
                        ElapsedTime: 0;
                    };
                    Transitions: {
                    };
                };
                OutlineColor: [0 0 0 0];
                SpawnTime: 0;
            }
            ActorInstance {
                Class: @"Defs/Entities/Ebola.ent.tk";
                Faction: Factions [Enemy];
                Controller: Null;
                CurrentHealth: 500;
                MaxSpeed: 247.6396;
                Weapon: Null;
                Name: Null;
                Position: [743.9265 237.2];
                Direction: [-0.9414236 -0.3372262];
                Velocity: [0 0];
                State: StateMachine {
                    State: EntStateId.Idle;
                    Instance: EntStateInstance {
                        Id: EntStateId.Idle;
                        Class: EntStateClass {
                            Name: Null;
                            Sprite: Sprite {
                                ElapsedTime: 39426;
                                FrameCount: 4;
                                FrameLength: 100;
                                TotalLength: 400;
                                IsLooping: True;
                                Texture: "Data\\Textures/Entities/Ebola.png";
                                Width: 54;
                                Height: 16;
                                Size: [54 16];
                                ClipRect: [0 0 108 32];
                                Origin: [27 8];
                                Tween: TweenStyle.Overlap;
                                ShrinkToFit: True;
                            };
                            Radius: 27;
                        };
                        ElapsedTime: 0;
                    };
                    Transitions: {
                    };
                };
                OutlineColor: [154 205 50 255];
                SpawnTime: 0;
            }
        ];
        fluids: [];
        elapsedTime: 68503.179;
        timeScale: 1;
    };
}