TrailClass {
    MaxPoints: 400;
    Color: Color.White;
    Sprite: {
        texture: @"Effects/Trails/Lightning.png";
    }

    Width: {
        Values: [
            [0 0]
            [0.2 40]
            [0.8 40]
            [1 0]
        ];
    };

    Jitter: [-20 20];
    SkipChance: 50%;
    CaptureDelay: 240Hz;
    LifeSpan: 0.5sec;
}

Function {
	Type [
		Linear
		Exponential
		Logarithmic
		Sinusoidal
	]

	Scale

	Bounds
	BoundsMode
}