GunClass {
    MaxAmmo: 100;
	RoundsPerBurst: 1;
    ProjectilesPerRound: 10;
    MaxBursts: 0;
    Projectile: @"Weapons/Projectiles/Missile.ent.tk";
    ErrorAngle: [-8deg 8deg];

    ChargeTime: 0msec;
    DischargeTime: 300msec;

    DischargeEffect: { #move to spawn effect on projectile?
        Effects: [
            ParticleEffect {
                Class: {
                    Graphic: {
                        Texture: @"./MuzzleFlash.png";
                        width: 48;
                        height: 48;
                        frameLength: 100msec;
                        frameCount: 4;
                        Center: true;
                    };
                    Blend: BlendState.AlphaBlend;
                    InitialSpeed: [0 0];
                    Drag: 1.3;
                    lifetime: [400msec 400msec];
                }
                Count: [10 20];
                Spread: [-30deg 30deg];
            };

            SoundImpulse {
                Permutations: [
                    SoundClass {
                        sound: "open_fx.ogg";
                        gain: 0.1;
                    }
                ]
            }
        ]
    }
}