GunClass {
    Projectile: @"Weapons/Projectiles/Missile.ent.tk";

    MaxAmmo: 10;
    RoundsPerBurst: 4;
    #ProjectilesPerRound: 6;
    MaxBursts: 0;
    BurstCooldownTime: 400msec;
    ChargeTime: 0sec;
    DischargeTime: 50msec;
    CooldownTime: 0sec;
    CanAlwaysCharge: true;
    ErrorAngle: [-2deg 2deg];

    DischargeEffect: { #move to spawn effect on projectile?
        Effects: [
            ParticleEffect {
                Class: {
                    Sprite: {
                        Texture: @"./MuzzleFlash.png";
                        width: 48;
                        height: 48;
                        frameLength: 40msec;
                        frameCount: 4;
                        Center: true;
                    };
                    Blend: BlendState.AlphaBlend;
                    InitialSpeed: [0 0];
                    Drag: 1.3;
                    lifetime: [160msec 160msec];
                }
                Count: [3 12];
                Spread: [-30deg 30deg];
            };

            SoundImpulse {
                Class: {
                    sound: @"open_fx.ogg";
                    gain: 0.1;
                }
            }
        ]
    }
}