Actor {
    primaryWeapon: Null;
    altWeapon: Null;
    MaxHealth: 100;
    States: { };
    CurrentState: EntState Idle;
    MaxSpeed: 400;
    MoveForce: 600;
    IsEnabled: True;
    AlwaysActive: False;
    Radius: 21;
    IsPhysical: True;
    IgnoreTrace: False;
    States: {
        Idle: GraphicSave {
            texture: "Textures/Entities/Astrovirus.png";
            width: 42;
            height: 42;
            origin: [21 21];
            frameCount: 6;
            frameTime: 100;
            isLooping: True;
            isRunning: True;
            tween: TweenStyle Overlap;
        };
    };
}