Actor {
    primaryWeapon: Null;
    altWeapon: Null;
    CurrentHealth: 0;
    MaxHealth: 0;
    States: {
    };
    CurrentState: Null;
    FieldOfView: 2.356194;
    MaxSpeed: 0;
    MoveForce: 0;
    Name: Null;
    Position: [0 0];
    Direction: [1 0];
    Velocity: [0 0];
    IsEnabled: True;
    AlwaysActive: False;
    AlwaysUpright: True;
    Radius: 16;
    IsPhysical: True;
    IgnoreTrace: False;
    Sprite: Sprite {
        texture: "Textures/Entities/InfectedCell.png";
        width: 32;
        height: 32;
        clipRect: [0 0 256 96];
        origin: [16 16];
        FrameCount: 8;
        FrameLength: 100;
        IsLooping: True;
        Tween: TweenStyle Overlap;
    };
    OutlineColor: [0 0 0 0];
}