List {
	Name: "SettingsMenu";
	Style: null;
	Direction: Direction.Vertical;
	HorizontalAlignment: Alignment.Center;
	VerticalAlignment: Alignment.Center;
	Margin: 50;

	Children: [
		Static {
			Text: "Settings";
			Style: "Header";
		};

		Static {
			Text: "coming soon™️";
			Style: "Button";
		};

		Static {
			Text: "Back";
			EventCommands: {
				Click: ["WizardTransition" "MainMenu"];
			};
			Style: "Button";
	 	};
	];
};