List {
	Name: "SettingsMenu";
	Styles: "MainMenu";
	HorizontalAlignment: Alignment.Center;
	VerticalAlignment: Alignment.Center;

	Children: [
		Static {
			Text: "Settings";
			Styles: "Header";
		};

		Static {
			Text: "coming soon™️";
			Styles: "Button";
		};

		Static {
			Text: "Back";
			EventCommands: {
				Click: ["WizardTransition" "MainMenu"];
			};
			Styles: "Button";
	 	};
	];
};