ActorClass {
    Name: "Astrovirus";
    MaxHealth: 40;
    DefaultFaction: Factions [Enemy Common];

	States: {
        Idle: {
            Sprite: {
            	texture: "Textures/Entities/Astrovirus.png";
                width: 42;
                height: 42;
                origin: [21 21];
                FrameCount: 6;
                FrameLength: 100;
                IsLooping: True;
                Tween: TweenStyle [Overlap];
            };
            Sound: { };
        };
        Dead: {
            Sprite: {
            	texture: "Textures/Entities/InfectedCell.png";
                width: 42;
                height: 42;
                origin: [21 21];
                FrameCount: 4;
                FrameLength: 100;
                IsLooping: True;
                Tween: TweenStyle [Overlap];
            };
            Sound: { };
        };
    };

    FieldOfView: 2.356194;
    MaxSpeed: [200 400];
    MoveForce: 500;
    AlwaysActive: false;
    IsPhysical: true;
    IgnoreTrace: false;
    AlwaysDrawUpright: true;
}
