MapClass {
    Name: Null;
    TileSize: 48;
    TilesImage: "Tilesets/tiles.png";
    Tiles: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0];
    Width: 8;
    Height: 8;
    InitialState: {
        Entities: [
            {
                Class: @"Actors/Player.ent.tk";
                Position: [192 191];
                Forward: [1 0];
            }
        ];
        fluids: [];
    };
}