ProjectileClass {
    Name: "Plasma rocket";
    DestroyIfOffscreen: True;
    IgnoreTrace: True;
    Drag: 0;
    CanDamageSource: false;
    InheritSourcePhysics: false;

    MuzzleVelocity: 10500;
    MagnetismAnglePerSecond: 1400deg;

    #*FadeEffect: {
        Effects: [
            EntityEffect {
                Entity: @.;
                Count: 1;
                Spread: -30deg;
                Speed: 500;
            }
            EntityEffect {
                Entity: @.;
                Count: 1;
                Spread: 30deg;
                Speed: 500;
            }
        ];
    }*#


    Trail: {
        MaxPoints: 200;
        Color: {
            Values: [
                [0 [240 192 255 255]];
                [1 Color.White];
            ];
        };
        Sprite: @"Effects/Trails/Lightning.png";
        LifeSpan: 0.1sec;
        CaptureDelay: 3000hz;
        Width: {
            Values: [
                [0 0];
                [0.8 12];
                [1 4];
            ]
        };
        Jitter: [-10 10];
    }
	#*
    Animations: {
        Idle: {
            Sprite: {
                Texture: @"./Antibody.png";
            };
            #Effect: @"Effects/Shards.fx.tk";
        }
    }*#
}