ProjectileClass {
    Name: "Plasma rocket";
    MuzzleVelocity: 1500;
    DestroyIfOffscreen: True;
    IgnoreTrace: True;
    Drag: 0.4;
    MinimumSpeed: 300;
    CanDamageSource: true;
    InheritSourcePhysics: true;    

    #*FadeEffect: {
        Effects: [
            EntityEffect {
                Entity: @.;
                Count: 1;
                Spread: -30deg;
                Speed: 500;
            }
            EntityEffect {
                Entity: @.;
                Count: 1;
                Spread: 30deg;
                Speed: 500;
            }
        ];
    }*#


    Trail: {
        MaxPoints: 200;
        Color: Color [240 192 255 255];
        Sprite: @"Effects/Trails/Lightning.png";
        LifeSpan: 0.5sec;
        CaptureDelay: 300hz;
        Width: {
            Values: [
                [0 0];
                [0.8 12];
                [1 4];
            ]
        };
        Jitter: [-3 3];
    }

    Animations: {
        Idle: {
            Sprite: {
                Texture: @"./Antibody.png";
            };
            #Effect: @"Effects/Shards.fx.tk";
        }
    }
}