EffectsClass {
	Effects: [
		ParticleEffect {
            Class: {
                Sprite: {
                    Texture: @"Effects/Trail.png"
                    Tween: TweenStyle.Overlap;
                };
                Blend: BlendState.Additive;
                InitialSpeed: [50 100];
                LifeSpan: [0.2sec 0.5sec];
            }
            Count: [0 3];
            Spread: [-0.9pi -1.1pi];
            Radius: 3;
        }
	]
}