[
    ParticleEffect {
        Class: {
            Graphic: {
                Texture: "Textures/Particles/Blood.png"
                FrameCount: 6;
                Width: 10;
                Height: 10;
                FrameLength: 100msec;
                Center: true;
            };
            Blend: BlendState.AlphaBlend;
            ColorOverTime: {
                start: Color.White;
                end: Color.Transparent;
            }
            InitialSpeed: [20 40];
            lifetime: [1sec 3sec];
        }
        Count: [10 200];
    }
    ParticleEffect {
        Class: {
            Graphic: {
                Texture: "Textures/Particles/trail.png"
                Width: 8;
                Height: 8;
                Center: true;
            };
            Blend: BlendState.Additive;
            AngleOverTime: {
                start: 0;
                end: 4pi;
            };
            ColorOverTime: {
                Curve: {
                    Keys: [
                        CurveKey {
                            Position: 0;
                            Value: 0;
                        }
                        CurveKey {
                            Position: 0.5;
                            Value: 0;
                        }
                        CurveKey {
                            Position: 1;
                            Value: 1;
                        }
                    ]
                }
                start: Color.White;
                end: Color.Red;
            }
            InitialSpeed: [10 50];
            lifetime: [2sec 5sec];
        }
        Count: [10 50];
    }
    FluidEffect {
        Class: @"Defs/Fluids/Blood.fluid.tk";
        Speed: [5 20];
        Count: [10 20];
    }
    SoundImpulse {
        Permutations: [
            SoundClass {
                sound: "Sounds/open_fx.ogg";
                gain: 0.1;
            }
        ]
    }
]