Actor {
    primaryWeapon: Null;
    altWeapon: Null;
    CurrentHealth: 0;
    MaxHealth: 0;
    States: { };
    CurrentState: Null;
    FieldOfView: 2.356194;
    MaxSpeed: 0;
    MoveForce: 0;
    Position: [0 0];
    Direction: [1 0];
    Velocity: [0 0];
    IsEnabled: True;
    AlwaysActive: False;
    Radius: 48;
    IsPhysical: True;
    IgnoreTrace: False;
    Sprite: Graphic {
        texture: "Textures/Entities/Test.png";
        width: 96;
        height: 96;
        ClipRect: [0 0 576 192];
        origin: [48 48];
        FrameCount: 6;
        FrameTime: 100;
        IsLooping: True;
        Tween: TweenStyle Overlap;
    };
    OutlineColor: [0 0 0 0];
}