WeaponPickupClass {
    Name: "Big fucking test gun";

	Weapon: @"Weapons/bfg.wpn.tk";

    Animations: {
        Idle: {
        	Sprite: {
                texture: @"./TestGuns.png";
                width: 64;
                height: 64;
                ClipRect: [192 0 64 64];
            };
            AlwaysDrawUpright: true;
        };
    };
    DestructionEffect: @"./Pickup.fx.tk";
}