WeaponPickupClass {
    Name: "Big fucking test gun";

	Weapon: GunInstance {
		Class: @"Weapons/bfg.wpn.tk";
		AmmoCount: 10000;
	}

    Animations: {
        Idle: {
        	Sprite: {
                texture: @"./TestGuns.png";
                width: 64;
                height: 64;
                ClipRect: [192 0 64 64];
            };
        };
    };
    DestructionEffect: @"./Pickup.fx.tk";
}