WeaponPickupClass {
    Name: "Some boss gun";

	Weapon: @"Weapons/Boss.wpn.tk";

    Animations: {
        Idle: {
        	Sprite: {
                texture: @"./TestGuns.png";
                width: 64;
                height: 64;
                ClipRect: [192 64 64 64];
            };
            AlwaysDrawUpright: true;
        };
    };
    SpawnEffect: @"./PickupSpawn.fx.tk";
    DestructionEffect: @"./Pickup.fx.tk";
}