WeaponPickupClass {
    Name: "Grenade launcher test gun";

	Weapon: @"Weapons/GrenadeLauncher.wpn.tk";

    Animations: {
        Idle: {
        	Sprite: {
                texture: @"./TestGuns.png";
                width: 64;
                height: 64;
                ClipRect: [0 64 64 64];
            };
            AlwaysDrawUpright: true;
        };
    };

    DestructionEffect: @"./Pickup.fx.tk";
}