WeaponPickupClass {
    Name: "Machine gun test gun";

	Weapon: GunInstance {
		Class: @"Weapons/mg.wpn.tk";
		AmmoCount: 10000;
	}

    Animations: {
        Idle: {
        	Sprite: {
                texture: @"./TestGuns.png";
                width: 64;
                height: 64;
                ClipRect: [128 64 64 64];
            };
        };
    };
    DestructionEffect: @"./Pickup.fx.tk";
}