WeaponPickupClass {
    Name: "Particle fx test gun";

	Weapon: @"Weapons/Flamethrower.wpn.tk";

    Animations: {
        Idle: {
        	Sprite: {
                texture: @"./TestGuns.png";
                width: 64;
                height: 64;
                ClipRect: [128 0 64 64];
            };
            AlwaysDrawUpright: true;
        };
    };

    DestructionEffect: @"./Pickup.fx.tk";
}