WeaponPickupClass {
	Weapon: @"Weapons/Test.wpn.tk";

    Animations: {
        Idle: {
        	Sprite: {
                texture: @"./TuberPickup.png";
                width: 48;
                height: 48;
                FrameCount: 6;
                FrameLength: 100;
                IsLooping: True;
                Tween: TweenStyle [Sequential];
            };
        };
    };

    DestructionEffect: @"./Pickup.fx.tk";
}