WeaponPickupClass {
	Weapon: GunInstance {
		Class: @"Weapons/Test.wpn.tk";
		AmmoCount: 1000;
	}

    Animations: {
        Idle: {
        	Sprite: {
                texture: @"./TuberPickup.png";
                width: 48;
                height: 48;
                FrameCount: 6;
                FrameLength: 100;
                IsLooping: True;
                Tween: TweenStyle [Sequential];
            };
        };
    };

    DestructionEffect: @"./Pickup.fx.tk";
}