

#*List {
	BorderColor: [192 192 192 128];
	Direction: Direction.Vertical;
	HorizontalAlignment: Alignment.Middle;
	VerticalAlignment: Alignment.Middle;
	Children: [
		Static { Text: 1; };
		Static { Text: 2; };
		Static { Text: 3; };
		Static { Text: 4; };
	]
};*#

ScrollBox {
	Name: "Container";
	#HorizontalAlignment: Alignment.Stretch;
	#VerticalAlignment: Alignment.Stretch;
	HorizontalAlignment: Alignment.Middle;
	VerticalAlignment: Alignment.Middle;
	Size: 400;
	#Padding: 20;
	BorderColor: Color.Gray;

	ScrollBarTemplate: {
		Padding: 0;
		BorderColor: Color.Gray;
		ThumbColor: [192 192 192 128];
	}

	Children: [
		Table {
			Name: "Form";
			Margin: [10 20];
			ColumnCount: 2;
			#BorderColor: [255 220 0 255];
			#CellColor: [0 255 192 32];

			Children: [

				Static { Text: "Static"; };
				Static {
					Name: "Static";
					Text: "Static";
					BorderColor: [192 192 192 128];
					HorizontalAlignment: Alignment.Stretch;
					Padding: 10;
					Position: 10;
				};
				
				Static { Text: "Button"; };
				Static {
					Name: "Button";
					Text: "Button";
					OnClickCommand: "undefined";
					BorderColor: [192 192 192 128];
					Padding: 10;
				};

				Static { Text: "CheckBox"; };
				CheckBox {
					Name: "CheckBox";
					Text: "CheckBox";
					BorderColor: [192 192 192 128];
					Padding: 10;
				};

				Static { Text: "TrackBar"; };
				TrackBar {
					Name: "TrackBar";
					BorderColor: [192 192 192 128];
					Minimum: 0;
					Maximum: 100;
					Value: 50;
					Increment: 1;
					Padding: 10;
				};

				Static { Text: "Graphic"; };
				Graphic {
					Name: "Graphic";
					Sprite: @"UI/test/test.spr.tk";
					BorderColor: [192 192 192 128];
					Padding: 10;
				};

				Static { Text: "NumericInput"; };
				NumericInput {
					Name: "NumericInput";
					BorderColor: [192 192 192 128];
					Padding: 10;
				};

				Static { Text: "TextInput"; };
				TextInput {
					Name: "TextInput";
					BorderColor: [192 192 192 128];
					Padding: 10;
				};

				Static { Text: "FileInput"; };
				FileInput {
					Name: "FileInput";
					BorderColor: [192 192 192 128];
					Padding: 10;
				};

				# meter
			
				Static { Text: "Horizontal\nList"; };
				List {
					Name: "HorizontalList";
					BorderColor: [192 192 192 128];
					Direction: Direction.Horizontal;
					Children: [
						Static { Text: 1; };
						Static { Text: 2; };
						Static { Text: 3; };
						Static { Text: 4; };
					]
					Padding: 10;
				};

				Static { Text: "Vertical\nList"; };
				List {
					Name: "VerticalList";
					BorderColor: [192 192 192 128];
					Direction: Direction.Vertical;
					Children: [
						Static { Text: 1; };
						Static { Text: 2; };
						Static { Text: 3; };
						Static { Text: 4; };
					]
					Padding: 10;
				};

			]
		}
	]
}