List {
	Name: "A";
	Padding: [10 10];
	Margin: 10;
	backgroundColor: [32 32 128];
	HorizontalAlignment: Alignment.Middle;
	VerticalAlignment: Alignment.Middle;
	Children: [
		Static {
			Name: "B";
			BackgroundColor: [0 192 255];
			Width: 100;
			Height: 100;
		}
		List {
			Name: "C";
			BackgroundColor: [255 192 0];
			Padding: [10 10];
			Children: [
				Static {
					Name: "D";
					BackgroundColor: [192 255 0];
					Width: 100;
					Height: 100;
				}
			]
		}
	]
}

List {
	Name: "Lost";
	Width: 400;
	Padding: [5 5];
	Margin: 10;
	BorderColor: color.Red;
	HorizontalAlignment: Alignment.Middle;
	VerticalAlignment: Alignment.Middle;
	BackgroundColor: [80 80 128 255];
	Direction: Direction.Vertical;

	Children: [
		Static {
			Name: "A";
			Text: "asdf";
			Padding: [10 10];
			BorderColor: color.Black;
			BackgroundColor: [0 238 255 255];

			OnClickCommand: 'asdf';
		};

		CheckBox {
			Name: "B";
			Text: "moo";
			BorderColor: color.Green;
			Padding: [20 20];
			OnClickCommand: 'asdf';
		}

		TextInput {
			Name: "C";
			padding: 10;
		}

		Static {
			Name: "D";
			Text: "xyzzy xyzzy xyzzy xyzzy xyzzy xyzzy xyzzy xyzzy xyzzy xyzzy xyzzy";
			BackgroundColor: Color.Tomato;
			Height: 100;
			HorizontalAlignment: Alignment.Stretch;
			Padding: [20 20];
		}

		Static {
			Name: "E";
			Text: "%^&*";
			BackgroundColor: Color.Orange;
			Height: 100;
			Width: 200;
			HorizontalAlignment: Alignment.Middle;
			Padding: [20 20];
		}
	]
}