#*ScrollBox {
	Size: [400 400];
	BorderColor: [0 40 100];
	HorizontalAlignment: Alignment.Middle;
	VerticalAlignment: Alignment.Middle;

	ScrollBarUI: {
		BorderColor: [255 255 255 64];
		ThumbColor: Color.LightSteelBlue;
		Padding: [2 2];
	}

	Children: [
		List {
			Children: [
				Static { Text: "abc"; Size: [100 100]; BackgroundColor: ColorUtil.RandomColor; };
				Static { Text: "def"; Size: [200 100]; BackgroundColor: ColorUtil.RandomColor; };
				Static { Text: "ghi"; Size: [300 100]; BackgroundColor: ColorUtil.RandomColor; };
				Static { Text: "jkl"; Size: [400 100]; BackgroundColor: ColorUtil.RandomColor; };
				Static { Text: "mno"; Size: [500 100]; BackgroundColor: ColorUtil.RandomColor; };
				Static { Name: "foo"; Text: "zzz"; Size: [500 100]; BackgroundColor: ColorUtil.RandomColor; };

			]
		}
	]
}*#

Static {
	Name: "!";
	Width: 400;
	Height: 400;
	HorizontalAlignment: Alignment.Middle;
	VerticalAlignment: Alignment.Middle;
	BackgroundColor: [0 38 58];
	Children: [
		ScrollBox {
			Name: "a";
			HorizontalAlignment: Alignment.Stretch;
			Size: [NaN 300];
			Children: [
				ActorList {
					Name: "b";
					Container: List {
						Name: "c";
						Direction: Direction.Vertical;
						Margin: 10;
					}
					ItemUI: Static { Text: "AAA"; Size: [100 100]; };
					Items: [
						@"Actors/player.ent.tk";
						@"Actors/player.ent.tk";
						@"Actors/player.ent.tk";
						@"Actors/player.ent.tk";
						@"Actors/player.ent.tk";
					];
				};
			];
		};
	];
};