Table {
	Size: [600 600];
	HorizontalAlignment: Alignment.Middle;
	VerticalAlignment: Alignment.Middle;
	Padding: [10 10];
	Margin: 10;
	ColumnCount: 3;
	BackgroundColor: [40 0 100];

	Children: [
		Static { Text: "Cell 0A"; Name: "Cell 0A"; BackgroundColor: [40 100 200]; Width: 200px; Padding: [10 5]; };
		Static { Text: "Cell 0B"; Name: "Cell 0B"; BackgroundColor: [40 100 200]; Width: 200px; Padding: [10 5]; };
		Static { Text: "Cell 0C"; Name: "Cell 0C"; BackgroundColor: [40 100 200]; Width: 200px; Padding: [10 5]; };

		Static {
			Text: "Cell 1A";
			Name: "Cell 1A";
			Padding: [10 5];
			BackgroundColor: [40 100 200];
			HorizontalAlignment: Alignment.End;
		};
		Static {
			Text: "Cell 1B";
			Name: "Cell 1B";
			Padding: [10 5];
			BackgroundColor: [40 100 200];
			HorizontalAlignment: Alignment.End;
		};
		Static {
			Text: "Cell 1C";
			Name: "Cell 1C";
			Padding: [10 5];
			BackgroundColor: [40 100 200];
			HorizontalAlignment: Alignment.End;
		};

		Static {
			Text: "Cell 2A";
			Name: "Cell 2A";
			Padding: [10 5];
			Position: [100 20];
			BackgroundColor: [40 100 200];
			HorizontalAlignment: Alignment.Middle;
		};
		Static {
			Text: "Cell 2B";
			Name: "Cell 2B";
			Padding: [10 5];
			BackgroundColor: [40 100 200];
			HorizontalAlignment: Alignment.Middle;
		};
		Static {
			Text: "Cell 2C";
			Name: "Cell 2C";
			Padding: [10 5];
			BackgroundColor: [40 100 200];
			HorizontalAlignment: Alignment.Middle;
		};

		Static {
			Text: "Cell 3A";
			Name: "Cell 3A";
			Padding: [10 5];
			BackgroundColor: [40 100 200];
			HorizontalAlignment: Alignment.Start;
		};
		Static {
			Text: "Cell 3B";
			Name: "Cell 3B";
			Padding: [10 5];
			BackgroundColor: [40 100 200];
			HorizontalAlignment: Alignment.Start;
		};
		Static {
			Text: "Cell 3C";
			Name: "Cell 3C";
			Padding: [10 5];
			BackgroundColor: [40 100 200];
			HorizontalAlignment: Alignment.Start;
		};
	];
};