MaterialInteractions {
    Interactions: [
        ["Player" "Tiles" MaterialInteraction {
            Effect: @"Effects/trail.fx.tk";
        }]

        ["Brass" "*" MaterialInteraction {
            ReflectAngle: [-50deg 50deg];
            Effect: @"Effects/Sparks.fx.tk";
        }]

        ["Needle" "*" MaterialInteraction {
            Effect: @"Effects/Shards.fx.tk";
            ReflectAngle: [-50deg 50deg];
        }]
    ];
}