MaterialInteractions {
    Interactions: [
        ["Player" "Tiles" MaterialInteraction {
            Effect: @"Effects/trail.fx.tk";    
        }]
        
        ["Brass" "Target" MaterialInteraction {
            Effect: @"Effects/Sparks.fx.tk";    
        }]
        ["Brass" "Tiles" MaterialInteraction {
            Effect: @"Effects/Sparks.fx.tk";
        }]
        ["Brass" "" MaterialInteraction {
            Effect: @"Effects/Sparks.fx.tk";
        }]

        ["Needle" "Tiles" MaterialInteraction {
            Effect: @"Effects/Shards.fx.tk";
        }]
        ["Needle" "Target" MaterialInteraction {
            Effect: @"Effects/Shards.fx.tk";
        }]
        ["Needle" "" MaterialInteraction {
            Effect: @"Effects/Shards.fx.tk";
        }]
    ];
}