MaterialInteractions {
    Interactions: [
        ["Player" "Tiles" MaterialInteraction {
            Effect: @"Effects/trail.fx.tk";
        }]

        ["Brass" "*" MaterialInteraction {
            MaxBounceAngle: 25deg;
            Friction: 0.1;
            Effect: @"Effects/Sparks.fx.tk";
        }]

        ["Needle" "*" MaterialInteraction {
            Effect: @"Effects/Shards.fx.tk";
        }]
    ];
}