{
    SnapAngle: 45deg;

    RenderSettings: {
		DrawTiles: true;
        DrawEntities: true;
        DrawFluids: true;
        DrawReflections: true;
        DrawFluidReflectionMask: false;
        DrawDecals: true;
        DrawParticles: true;
        DrawTriggers: true;
        DrawLines: true;
        DrawGrids: true;
        DrawSectorsOnGrid: true;
        DrawBordersAroundNonDrawingEntities: true;
        DrawEntBoundingBoxes: true;
    };
}