ActorClass {
    Name: "Astrovirus";
    MaxHealth: 400;
    DefaultFactions: Factions.Enemy;

    FieldOfView: 2.356194;
    MaxSpeed: [300 800];
    MoveForce: 200;
    IsPhysical: true;
    IgnoreTrace: false;

    DefaultController: [AIController {
        DefaultBehaviors: [
            Behavior {
                Name: "Attach";
                RequisiteNotSenses: Senses [Attached];
                Tasks: [
                    FindClosestActor {
                        isAlly: false;
                        isSameClass: false;
                    };
                    MoveToTarget {
                        distance: 20;
                    };
                    AttachToTarget { };
                ];
            };
            Behavior {
                Name: "Explode";
                RequisiteSenses: Senses [Attached];
                Tasks: [
                    SetConditionOnTarget {
                        condition: @"Actors/Conditions/flameglow.cond.tk";
                        duration: 2sec;
                    }
                    Wait { duration: 2sec; }
                    Suicide {
                     # todo: effect
                     effect: @"Effects/Greensplosion.fx.tk";
                    }

                    #set condition to heat up and then explode after x seconds?
                ];
            };
        ];
    }];

	Animations: {
        Idle: {
            Sprite: {
            	texture: @"Actors/Astrovirus.png";
                width: 40;
                height: 40;
                origin: [20 20];
                FrameCount: 6;
                FrameLength: 50;
                IsLooping: True;
                Tween: TweenStyle [Overlap];
            };
            AlwaysDrawUpright: true;
            Sound: { };
        };
        Dead: {
            Sprite: {
            	texture: @"Actors/Astrovirus.png";
                width: 40;
                height: 40;
                origin: [20 20];
                ClipRect: [0 80 240 40];
                FrameCount: 6;
                FrameLength: 50;
                IsLooping: False;
                Tween: TweenStyle [Overlap];
            };
            AlwaysDrawUpright: true;
            Sound: { };
        };
    };
}
