ActorClass {
    Name: "Astrovirus";
    MaxHealth: 40;
    DefaultFaction: Factions [Enemy Common];

	States: {
        Idle: {
            Sprite: {
            	texture: "Actors/Astrovirus.png";
                width: 40;
                height: 40;
                origin: [20 20];
                FrameCount: 6;
                FrameLength: 50;
                IsLooping: True;
                Tween: TweenStyle [Overlap];
            };
            Sound: { };
        };
        Dead: {
            Sprite: {
            	texture: "Actors/Astrovirus.png";
                width: 40;
                height: 40;
                origin: [20 20];
                ClipRect: [0 80 240 40];
                FrameCount: 6;
                FrameLength: 50;
                IsLooping: False;
                Tween: TweenStyle [Overlap];
            };
            Sound: { };
        };
    };

    FieldOfView: 2.356194;
    MaxSpeed: [200 400];
    MoveForce: 500;
    IsPhysical: true;
    IgnoreTrace: false;
    AlwaysDrawUpright: true;
}
