ActorClass {
    Name: "Astrovirus";
    MaxHealth: 40;
    DefaultFaction: Factions [Enemy Common];

    FieldOfView: 2.356194;
    MaxSpeed: [50 200];
    MoveForce: 200;
    IsPhysical: true;
    IgnoreTrace: false;
    AlwaysDrawUpright: true;

    DefaultController: AIController {
        Behaviors: [
            FlowSeekBehavior { };

            TargetEnemyBehavior { };
            FocusBehavior { };
        ];
    };

	Animations: {
        Idle: {
            Sprite: {
            	texture: @"Actors/Astrovirus.png";
                width: 40;
                height: 40;
                origin: [20 20];
                FrameCount: 6;
                FrameLength: 50;
                IsLooping: True;
                Tween: TweenStyle [Overlap];
            };
            Sound: { };
        };
        Dead: {
            Sprite: {
            	texture: @"Actors/Astrovirus.png";
                width: 40;
                height: 40;
                origin: [20 20];
                ClipRect: [0 80 240 40];
                FrameCount: 6;
                FrameLength: 50;
                IsLooping: False;
                Tween: TweenStyle [Overlap];
            };
            Sound: { };
        };
    };
}
