ActorClass {
	Name: "Rhinovirus";
	MaxHealth: 5000;
    DefaultFaction: Factions [Enemy Boss];

    DefaultController: AIController {
        Behaviors: [
            ShootBehavior {};
            FocusBehavior {};
            TargetEnemyBehavior {
                SightDistance: 1000;
            };
        ];
    }

    DefaultWeapon: @"Weapons/Boss.wpn.tk";

    Animations: {
    	Idle: {
    		Sprite: {
				Texture: @"./Rhinovirus.png";
				Origin: [64 64];
				IsLooping: True;
    		};
    	};
    };
};