ActorClass {
	Name: "Rhinovirus";
	MaxHealth: 5000;
    DefaultFaction: Factions [Enemy Boss];

    DefaultController: AIController {
        Behaviors: [
            ShootBehavior {};
            TargetEnemyBehavior {};
        ];
    }

    DefaultWeapon: @"Weapons/Boss.wpn.tk";

    Animations: {
    	Idle: {
    		Sprite: {
				Texture: "Actors/Rhinovirus.png";
				Origin: [64 64];
				IsLooping: True;
    		};
    	};
    };
};