ActorClass {
    Name: "Practice Target";
    MaxHealth: 50000;
    DefaultFactions: Factions [Enemy];

    Animations: {
        Idle: {
            Sprite: @"./target.png";
            Material: "Target";
            AlwaysDrawUpright: true;
        };
    };

    DefaultController: [AIController {
    }];

    FieldOfView: 0.667pi;
    IsPhysical: True;
    IgnoreTrace: False;
}
