ActorClass {
	Name: "Fake laser weapon";
	MaxHealth: 5000;

    DefaultController: [AIController {
    }];

    DefaultWeapon: [GunClass {
        MaxAmmo: 0;
        Projectile: {
            Trail: @"Effects/Trails/Laser.trail.tk";
            MuzzleVelocity: 1E10;
            Damage: 100;
            Drag: 0;
        };
        DischargeTime: 100msec;
    }];

    Animations: {
    	Idle: {
    		Sprite: @"./turretA.png";
    	};
    };
};